site_name: "Mike's Notebook Wiki"
nav:
  - Home: index.md
  - Projects:
    - anderson-computer-consulting: 'anderson-computer-consulting/index.md'
    - devlog: 'devlog/index.md'
    - lrn-pxe: 'lrn-pxe/index.md'
    - lrn/tools: 'lrn_tools/index.md'
    - lrn/tools/packaging/lrn-tools-airgap-2.3.0: 'lrn_tools_packaging_lrn-tools-airgap-2.3.0/index.md'
    - mac-ops: 'mac-ops/index.md'
    - mac-ops/.pytest/cache: 'mac-ops_.pytest_cache/index.md'
    - mac-ops/venv/lib/python3.9/site-packages/flask/sansio: 'mac-ops_venv_lib_python3.9_site-packages_flask_sansio/index.md'
    - mac-ops/venv/lib/python3.9/site-packages/pip//vendor: 'mac-ops_venv_lib_python3.9_site-packages_pip__vendor/index.md'
    - mikes/notebook: 'mikes_notebook/index.md'
    - openclaw: 'openclaw/index.md'
    - openclaw-airgap: 'openclaw-airgap/index.md'
    - openclaw/apps/android: 'openclaw_apps_android/index.md'
    - openclaw/apps/ios: 'openclaw_apps_ios/index.md'
    - openclaw/apps/ios/fastlane/metadata: 'openclaw_apps_ios_fastlane_metadata/index.md'
    - openclaw/apps/macos: 'openclaw_apps_macos/index.md'
    - openclaw/docs/.generated: 'openclaw_docs_.generated/index.md'
    - openclaw/docs/.i18n: 'openclaw_docs_.i18n/index.md'
    - openclaw/extensions/bluebubbles: 'openclaw_extensions_bluebubbles/index.md'
    - openclaw/extensions/copilot-proxy: 'openclaw_extensions_copilot-proxy/index.md'
    - openclaw/extensions/diffs: 'openclaw_extensions_diffs/index.md'
    - openclaw/extensions/llm-task: 'openclaw_extensions_llm-task/index.md'
    - openclaw/extensions/lmstudio: 'openclaw_extensions_lmstudio/index.md'
    - openclaw/extensions/lobster: 'openclaw_extensions_lobster/index.md'
    - openclaw/extensions/memory-wiki: 'openclaw_extensions_memory-wiki/index.md'
    - openclaw/extensions/minimax: 'openclaw_extensions_minimax/index.md'
    - openclaw/extensions/nostr: 'openclaw_extensions_nostr/index.md'
    - openclaw/extensions/ollama: 'openclaw_extensions_ollama/index.md'
    - openclaw/extensions/open-prose: 'openclaw_extensions_open-prose/index.md'
    - openclaw/extensions/open-prose/skills/prose/examples: 'openclaw_extensions_open-prose_skills_prose_examples/index.md'
    - openclaw/extensions/open-prose/skills/prose/examples/roadmap: 'openclaw_extensions_open-prose_skills_prose_examples_roadmap/index.md'
    - openclaw/extensions/open-prose/skills/prose/lib: 'openclaw_extensions_open-prose_skills_prose_lib/index.md'
    - openclaw/extensions/sglang: 'openclaw_extensions_sglang/index.md'
    - openclaw/extensions/tlon: 'openclaw_extensions_tlon/index.md'
    - openclaw/extensions/twitch: 'openclaw_extensions_twitch/index.md'
    - openclaw/extensions/vllm: 'openclaw_extensions_vllm/index.md'
    - openclaw/extensions/voice-call: 'openclaw_extensions_voice-call/index.md'
    - openclaw/extensions/zalo: 'openclaw_extensions_zalo/index.md'
    - openclaw/extensions/zalouser: 'openclaw_extensions_zalouser/index.md'
    - openclaw/qa: 'openclaw_qa/index.md'
    - openclaw/qa/convex-credential-broker: 'openclaw_qa_convex-credential-broker/index.md'
    - openclaw/scripts/clawdock: 'openclaw_scripts_clawdock/index.md'
    - openclaw/src/hooks/bundled: 'openclaw_src_hooks_bundled/index.md'
    - openclaw/Swabble: 'openclaw_Swabble/index.md'
    - openclaw/vendor/a2ui: 'openclaw_vendor_a2ui/index.md'
    - openclaw/vendor/a2ui/renderers/angular: 'openclaw_vendor_a2ui_renderers_angular/index.md'
    - openclaw/vendor/a2ui/renderers/lit: 'openclaw_vendor_a2ui_renderers_lit/index.md'
    - openclaw/vendor/a2ui/specification/0.8/eval: 'openclaw_vendor_a2ui_specification_0.8_eval/index.md'
    - openclaw/vendor/a2ui/specification/0.8/json: 'openclaw_vendor_a2ui_specification_0.8_json/index.md'
    - openclaw/vendor/a2ui/specification/0.9/eval: 'openclaw_vendor_a2ui_specification_0.9_eval/index.md'
